### ISSUE TITLE
Package requirements issue

### ISSUE THREAD

**Issue by amelie-iska** [kuleshov-group/caduceus#30]
I am trying to run the following script:
```python
from transformers import AutoModelForMaskedLM, AutoTokenizer
import torch
import matplotlib.pyplot as plt
import numpy as np

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the model and tokenizer
model_name = "kuleshov-group/caduceus-ps_seqlen-131k_d_model-256_n_layer-16"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForMaskedLM.from_pretrained(model_name, trust_remote_code=True)
model.to(device)

# Input DNA sequence
dna_sequence = "ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC"

# Tokenize the input sequence
input_ids = tokenizer.encode(dna_sequence, return_tensors="pt").to(device)
sequence_length = input_ids.shape[1] - 2  # Excluding the special tokens

# List of DNA bases
dna_bases = list("ATCG")

# Initialize heatmap
heatmap = np.zeros((4, sequence_length))

# Calculate LLRs for each position and DNA base
for position in range(1, sequence_length + 1):
    # Mask the target position
    masked_input_ids = input_ids.clone()
    masked_input_ids[0, position] = tokenizer.mask_token_id
    
    # Get logits for the masked token
    with torch.no_grad():
        logits = model(masked_input_ids).logits
        
    # Calculate log probabilities
    probabilities = torch.nn.functional.softmax(logits[0, position], dim=0)
    log_probabilities = torch.log(probabilities)
    
    # Get the log probability of the wild-type base
    wt_base = input_ids[0, position].item()
    log_prob_wt = log_probabilities[wt_base].item()
    
    # Calculate LLR for each variant
    for i, base in enumerate(dna_bases):
        log_prob_mt = log_probabilities[tokenizer.convert_tokens_to_ids(base)].item()
        heatmap[i, position - 1] = log_prob_mt - log_prob_wt

# Compute the number of pairs
num_pairs = (sequence_length * (sequence_length - 1) * 4 * 4) // 2
print(f"Number of distinct LLR value pairs: {num_pairs}")

# Initialize arrays to store the pairs and their sums
pair_positions = np.zeros((num_pairs, 2), dtype=int)
pair_bases = np.zeros((num_pairs, 2), dtype=int)
pair_sums = np.zeros(num_pairs)

# Compute the sums of pairs of LLR values for distinct pairs of bases
index = 0
for i in range(sequence_length):
    for j in range(i + 1, sequence_length):
        for base1 in range(4):
            for base2 in range(4):
                pair_positions[index] = [i, j]
                pair_bases[index] = [base1, base2]
                pair_sums[index] = heatmap[base1, i] + heatmap[base2, j]
                index += 1

# Sort the pairs based on their sums
sorted_indices = np.argsort(pair_sums)

# Get the top 10 most beneficial and deleterious pairs
top_beneficial_indices = sorted_indices[-10:]
top_deleterious_indices = sorted_indices[:10]

# Print the results
print("Top 10 most beneficial pairs:")
for index in top_beneficial_indices:
    pos1, pos2 = pair_positions[index]
    base1, base2 = pair_bases[index]
    llr1, llr2 = heatmap[base1, pos1], heatmap[base2, pos2]
    print(f"({dna_sequence[pos1]}{pos1+1}{dna_bases[base1]}, {llr1:.2f}), ({dna_sequence[pos2]}{pos2+1}{dna_bases[base2]}, {llr2:.2f}), {llr1+llr2:.2f}")

print("\nTop 10 most deleterious pairs:")
for index in top_deleterious_indices:
    pos1, pos2 = pair_positions[index]
    base1, base2 = pair_bases[index]
    llr1, llr2 = heatmap[base1, pos1], heatmap[base2, pos2]
    print(f"({dna_sequence[pos1]}{pos1+1}{dna_bases[base1]}, {llr1:.2f}), ({dna_sequence[pos2]}{pos2+1}{dna_bases[base2]}, {llr2:.2f}), {llr1+llr2:.2f}")
```
However, even after running the pip install command for `mamba-ssm` I continue to get the following error:
```
(caduceus) [<user>@<host> variant-effects]$ python dna_mutation_pairs_effects.py
<path>/mambaforge/envs/caduceus/bin/python
<path>/mambaforge/envs/caduceus/lib/python3.8/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "dna_mutation_pairs_effects.py", line 13, in <module>
    model = AutoModelForMaskedLM.from_pretrained(model_name, trust_remote_code=True)
  File "<path>/mambaforge/envs/caduceus/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "<path>/mambaforge/envs/caduceus/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 489, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "<path>/mambaforge/envs/caduceus/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 315, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "<path>/mambaforge/envs/caduceus/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 180, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: mamba_ssm. Run `pip install mamba_ssm`
(caduceus) [<user>@<host> variant-effects]$ 
```
I've tried also using `pip install mamba_ssm` as suggested, but this does not work either. It seems `mamba-ssm` is listed whenever I run `pip list`, so I'm not sure what the issue is.

**Comment by yair-schiff** [comment]
Please try `pip install mamba-ssm` instead (i.e.,`-` dash instead of `_` underscore)

**Comment by amelie-iska** [comment]
I have tried that as well. It doesn't work.
