### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by JiaLonghao1997** [kuleshov-group/caduceus#58]
This is my running process: 
```python
/home1/jialh/metaHiC/LLMs/caduceus/train.py:702: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs", config_name="config.yaml")
CONFIG
├── train
│   └── seed: 2222                                                                                        
│       interval: step                                                                                    
│       monitor: test/loss                                                                                
│       mode: min                                                                                         
│       ema: 0.0                                                                                          
│       test: true                                                                                        
│       debug: false                                                                                      
│       ignore_warnings: false                                                                            
│       optimizer_param_grouping:                                                                         
│         bias_weight_decay: false                                                                        
│         normalization_weight_decay: false                                                               
│       state:                                                                                            
│         mode: null                                                                                      
│         n_context: 0                                                                                    
│         n_context_eval: 0                                                                               
│       ckpt: checkpoints/last.ckpt                                                                       
│       disable_dataset: false                                                                            
│       validate_at_start: false                                                                          
│       pretrained_model_path: null                                                                       
│       pretrained_model_strict_load: true                                                                
│       pretrained_model_state_hook:                                                                      
│         _name_: null                                                                                    
│       post_init_hook:                                                                                   
│         _name_: null                                                                                    
│       layer_decay:                                                                                      
│         _name_: null                                                                                    
│         decay: 0.7                                                                                      
│       gpu_mem: 41                                                                                       
│       global_batch_size: 1024                                                                           
│                                                                                                         
├── wandb
│   └── None                                                                                              
├── trainer
│   └── _target_: pytorch_lightning.Trainer                                                               
│       devices: 1                                                                                        
│       accelerator: gpu                                                                                  
│       accumulate_grad_batches: 1                                                                        
│       max_epochs: null                                                                                  
│       gradient_clip_val: 1.0                                                                            
│       log_every_n_steps: 10                                                                             
│       limit_train_batches: 1.0                                                                          
│       limit_val_batches: 0.125                                                                          
│       num_sanity_val_steps: 2                                                                           
│       num_nodes: 1                                                                                      
│       max_steps: 10000                                                                                  
│       precision: 16                                                                                     
│       val_check_interval: 10000                                                                         
│                                                                                                         
├── dataset
│   └── _name_: hg38                                                                                      
│       bed_file: /home1/jialh/metaHiC/LLMs/hyena-dna/data/hg38/human-sequences.bed                       
│       fasta_file: /home1/jialh/metaHiC/LLMs/hyena-dna/data/hg38/hg38.ml.fa                              
│       dataset_name: hg38                                                                                
│       tokenizer_name: char                                                                              
│       cache_dir: null                                                                                   
│       max_length: 1024                                                                                  
│       add_eos: true                                                                                     
│       batch_size: 1024                                                                                  
│       batch_size_eval: 2048                                                                             
│       num_workers: 12                                                                                   
│       shuffle: true                                                                                     
│       max_length_val: 1024                                                                              
│       max_length_test: 1024                                                                             
│       pad_max_length: null                                                                              
│       rc_aug: false                                                                                     
│       use_fixed_len_val: false                                                                          
│       mlm: true                                                                                         
│       mlm_probability: 0.15                                                                             
│                                                                                                         
├── optimizer
│   └── _name_: adamw                                                                                     
│       lr: 0.008                                                                                         
│       weight_decay: 0.1                                                                                 
│       betas:                                                                                            
│       - 0.9                                                                                             
│       - 0.95                                                                                            
│                                                                                                         
├── scheduler
│   └── _name_: cosine_warmup_timm                                                                        
│       t_in_epochs: false                                                                                
│       t_initial: 9000.0                                                                                 
│       lr_min: 0.0001                                                                                    
│       warmup_lr_init: 1.0e-06                                                                           
│       warmup_t: 1000.0                                                                                  
│       warmup_prefix: true                                                                               
│                                                                                                         
├── callbacks
│   └── learning_rate_monitor:                                                                            
│         logging_interval: step                                                                          
│       timer:                                                                                            
│         step: true                                                                                      
│         inter_step: false                                                                               
│         epoch: true                                                                                     
│         val: true                                                                                       
│       params:                                                                                           
│         total: true                                                                                     
│         trainable: true                                                                                 
│         fixed: true                                                                                     
│       model_checkpoint:                                                                                 
│         monitor: test/loss                                                                              
│         mode: min                                                                                       
│         save_top_k: 1                                                                                   
│         save_last: false                                                                                
│         dirpath: checkpoints/                                                                           
│         filename: test/loss                                                                             
│         auto_insert_metric_name: false                                                                  
│         verbose: true                                                                                   
│       model_checkpoint_every_n_steps:                                                                   
│         monitor: train/loss                                                                             
│         mode: min                                                                                       
│         save_top_k: 0                                                                                   
│         save_last: true                                                                                 
│         dirpath: checkpoints/                                                                           
│         filename: train/loss                                                                            
│         auto_insert_metric_name: false                                                                  
│         verbose: true                                                                                   
│         every_n_train_steps: 500                                                                        
│                                                                                                         
├── task
│   └── _name_: lm                                                                                        
│       loss:                                                                                             
│         _name_: cross_entropy                                                                           
│         ignore_index: 4                                                                                 
│       torchmetrics:                                                                                     
│       - perplexity                                                                                      
│       - num_tokens                                                                                      
│                                                                                                         
├── encoder
│   └── None                                                                                              
├── decoder
│   └── None                                                                                              
├── loader
│   └── num_workers: 128                                                                                  
│       pin_memory: true                                                                                  
│       drop_last: true                                                                                   
│                                                                                                         
└── model
    └── _name_: caduceus_lm                                                                               
        config:                                                                                           
          _target_: caduceus.configuration_caduceus.CaduceusConfig                                        
          d_model: 128                                                                                    
          n_layer: 4                                                                                      
          vocab_size: 12                                                                                  
          ssm_cfg:                                                                                        
            d_state: 16                                                                                   
            d_conv: 4                                                                                     
            expand: 2                                                                                     
            dt_rank: auto                                                                                 
            dt_min: 0.001                                                                                 
            dt_max: 0.1                                                                                   
            dt_init: random                                                                               
            dt_scale: 1.0                                                                                 
            dt_init_floor: 0.0001                                                                         
            conv_bias: true                                                                               
            bias: false                                                                                   
            use_fast_path: true                                                                           
          rms_norm: true                                                                                  
          fused_add_norm: true                                                                            
          residual_in_fp32: false                                                                         
          pad_vocab_size_multiple: 8                                                                      
          norm_epsilon: 1.0e-05                                                                           
          initializer_cfg:                                                                                
            initializer_range: 0.02                                                                       
            rescale_prenorm_residual: true                                                                
            n_residuals_per_layer: 1                                                                      
          bidirectional: true                                                                             
          bidirectional_strategy: add                                                                     
          bidirectional_weight_tie: true                                                                  
          rcps: true                                                                                      
          complement_map: null                                                                            
                                                                                                          
Global seed set to 2222
[2024-12-22 12:24:29,762][__main__][INFO] - Instantiating callback <src.callbacks.timer.Timer>
[2024-12-22 12:24:29,765][__main__][INFO] - Instantiating callback <src.callbacks.params.ParamsLog>
[2024-12-22 12:24:29,766][__main__][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2024-12-22 12:24:29,768][__main__][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2024-12-22 12:24:29,769][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
[2024-12-22 12:24:29,895][src.dataloaders.genomics][INFO] - **Using Char-level tokenizer**
[2024-12-22 12:24:30,085][__main__][INFO] - config.train.ckpt='checkpoints/last.ckpt' fsspec_exists(config.train.ckpt)=False
[2024-12-22 12:24:30,254][src.dataloaders.genomics][INFO] - **Using Char-level tokenizer**
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Hyperparameter groups: [{'weight_decay': 0.0}]
[2024-12-22 12:24:30,892][__main__][INFO] - Optimizer group 0 | 37 tensors | weight_decay 0.1
[2024-12-22 12:24:30,892][__main__][INFO] - Optimizer group 1 | 33 tensors | weight_decay 0.0

  | Name               | Type                | Params
-----------------------------------------------------------
0 | model              | CaduceusForMaskedLM | 541 K 
1 | encoder            | Identity            | 0     
2 | decoder            | Identity            | 0     
3 | train_torchmetrics | MetricCollection    | 0     
4 | val_torchmetrics   | MetricCollection    | 0     
5 | test_torchmetrics  | MetricCollection    | 0     
-----------------------------------------------------------
541 K     Trainable params
0         Non-trainable params
541 K     Total params
1.083     Total estimated model params size (MB)
Sanity Checking DataLoader 0: 100%|█████████████████████████████████████████| 2/2 [00:06<00:00,  3.37s/it]Error executing job with overrides: ['experiment=hg38/hg38', 'callbacks.model_checkpoint_every_n_steps.every_n_train_steps=500', 'dataset.max_length=1024', 'dataset.batch_size=1024', 'dataset.mlm=true', 'dataset.mlm_probability=0.15', 'dataset.rc_aug=false', 'dataset.bed_file=/home1/jialh/metaHiC/LLMs/hyena-dna/data/hg38/human-sequences.bed', 'dataset.fasta_file=/home1/jialh/metaHiC/LLMs/hyena-dna/data/hg38/hg38.ml.fa', 'model=caduceus', 'model.config.d_model=128', 'model.config.n_layer=4', 'model.config.bidirectional=true', 'model.config.bidirectional_strategy=add', 'model.config.bidirectional_weight_tie=true', 'model.config.rcps=true', 'optimizer.lr=8e-3', 'train.global_batch_size=1024', 'trainer.max_steps=10000', '+trainer.val_check_interval=10000', 'wandb=null']
Traceback (most recent call last):
  File "/home1/jialh/metaHiC/LLMs/caduceus/train.py", line 717, in main
    train(config)
  File "/home1/jialh/metaHiC/LLMs/caduceus/train.py", line 682, in train
    trainer.fit(model)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1190, in _run_train
    self._run_sanity_check()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1262, in _run_sanity_check
    val_loop.run()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/caduceus_env/lib/python3.8/multiprocessing/popen_fork.py", line 68, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by yair-schiff** [comment]
I don't believe I ever hit this error. Are you seeing it consistently or just intermittently? Is it possible you have some zombie/background processes from other runs that need to be killed? Do you also see this issue if `num_workers` is set to `0`?

**Comment by leannmlindsey** [comment]
@JiaLonghao1997 I compared your output above to my logs and your data loader, number of workers is set much higher than mine.  Mine was 16 and yours is 128 (see below). I would check your slurm file or your train.py to see if you are overriding the parameters set in the github code.

from above:
── loader
│   └── num_workers: 128

**Comment by JiaLonghao1997** [comment]
> number of workers

Thanks, 128 is the default setting in the github repository. When I set number of workers to 16, everything works fine.
